const abc = [
 {
  "id": 1,
  "pid": "A001",
  "name": "Burkhaus Queen Upholstered Panel Bed",
  "price": 1000,
  "brand": "Ashley",
  "description": "Includes sleigh headboard, panel footboard and rails\n\nMade with select oak veneer, engineered wood, solid wood components and cast resin components\n\nAntiqued white finish with grain texture\n\nFoundation/box spring required, sold separately \n\nMattress available, sold separately \n\nAssembly required\n\nElegant, timeless furnishings take your bedroom to the next level. Nothing does that better than the Robbinsdale queen sleigh bed. The antiqued white finish with a wonderful grain texture radiates sophistication, making this the perfect piece to round out the ultimate tasteful bedroom.\n",
  "des-short": "Elegant, timeless furnishings take your bedroom to the next level. Nothing does that better than the Robbinsdale queen sleigh bed. The antiqued white finish with a wonderful grain texture radiates sophistication, making this the perfect piece to round out the ultimate tasteful bedroom.",
  "material": "Velvet",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 8,
  "image": "./img/img_product/A001.jpg",
  "image-detail": "./img/img_product/A001-d.jpg",
  "path-doc": "./product-detail-doc/A001.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "user1", "comment": "This product is very high quality and reasonably priced. I am very satisfied with it. I rate 5 stars", "star": 5, "time": "01/09/2023 07:05:00"},{"user": "user2", "comment": "Bad, I don’t like it", "star": 5, "time": "01/10/2023 21:05:30"},{"user": "user3", "comment": "nice", "star": 4, "time": "06/10/2023 21:50:30"}]
 },
 {
  "id": 2,
  "pid": "A002",
  "name": "Robbinsdale Queen Sleigh Bed",
  "price": 1000,
  "brand": "Aaron",
  "description": "Includes sleigh headboard, panel footboard and rails\n\nMade with select oak veneer, engineered wood, solid wood components and cast resin components\n\nAntiqued white finish with grain texture\n\nFoundation/box spring required, sold separately \n\nMattress available, sold separately \n\nAssembly required\n\nElegant, timeless furnishings take your bedroom to the next level. Nothing does that better than the Robbinsdale queen sleigh bed. The antiqued white finish with a wonderful grain texture radiates sophistication, making this the perfect piece to round out the ultimate tasteful bedroom.\n",
  "des-short": "Elegant, timeless furnishings take your bedroom to the next level. Nothing does that better than the Robbinsdale queen sleigh bed. The antiqued white finish with a wonderful grain texture radiates sophistication, making this the perfect piece to round out the ultimate tasteful bedroom.",
  "material": "Velvet",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 3,
  "image": "./img/img_product/A002.jpg",
  "image-detail": "./img/img_product/A002-d.jpg",
  "path-doc": "./product-detail-doc/A002.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "markzuckerberg", "comment": "Good product, great quality, fast shipping, 5 star store", "star": 5, "time": "06/10/2023 20:40:10"},{"user": "sergeybrin", "comment":"The product is very beautiful, very good quality, looks very durable, feels very luxurious", "star": 5, "time": "02/10/202312:01:01"},{"user": "larrypage", "comment":"Fast delivery. Correct model. Beautiful for the price. Please rest assured to buy", "star": 5, "time": "20/10-2023 17:30:01"}]
 },
 {
  "id": 3,
  "pid": "A003",
  "name": "Welltern California King Panel Bed",
  "price": 1200,
  "brand": "Dunelm Group",
  "description": "For those who love the classic profiles of traditional design—but want to forego the overly formal details—behold this California king panel bed. Saber legs, along with the framed headboard's gracefully shaped crown and stylish half round posts, add distinctive touches. \nA rich layered black finish on the textured wood grain surface with rubbed-through edges offers a subtle sense of gently aged charm. What a beautiful take on urban revival design.",
  "des-short": "What a beautiful take on urban revival design.",
  "material": "Velvet",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 8,
  "image": "./img/img_product/A003.jpg",
  "image-detail": "./img/img_product/A003-d.jpg",
  "path-doc": "./product-detail-doc/A003.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "customer1", "comment": "Great product! The quality exceeded my expectations.", "star": 4, "time": "02/15/2023 10:30:00"}, {"user": "customer2", "comment": "Not bad, but a bit pricey for the features it offers.", "star": 3, "time": "02/16/2023 14:20:45"}, {"user": "customer3", "comment": "Impressive design, I love it!", "star": 5, "time": "02/17/2023 18:45:20"}]
 },
 {
  "id": 4,
  "pid": "A004",
  "name": "Lombardia Sofa",
  "price": 500,
  "brand": "Aaron",
  "description": "Premium in every aspect, this sofa is crafted with elevated comfort in mind. Every detail, including the supple combination leather and faux leather upholstery, has been designed and refined to look and feel luxurious.\nWhether you use it as an inviting place to lounge or pair it with the matching loveseat and accent chair, it's sure to be a rich addition to your home.\n",
  "des-short": "Whether you use it as an inviting place to lounge or pair it with the matching loveseat and accent chair, it's sure to be a rich addition to your home.",
  "material": "Leather",
  "size": "200*100*50",
  "room": "LivingRoom",
  "quantity": 7,
  "image": "./img/img_product/A004.jpg",
  "image-detail": "./img/img_product/A004-d.jpg",
  "path-doc": "./product-detail-doc/A004.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "buyerA", "comment": "Reasonably priced and durable. Satisfied with the purchase.", "star": 4, "time": "03/05/2023 08:15:00"},{"user": "buyerB", "comment": "Could be better. Not the best value for money.", "star": 2, "time": "03/06/2023 12:40:30"},{"user": "buyerC", "comment": "Simple yet elegant design. Happy with my choice.", "star": 5, "time": "03/07/2023 16:55:15"}]
 },
 {
  "id": 5,
  "pid": "A005",
  "name": "Lannistone",
  "price": 700,
  "brand": "Ashley",
  "description": "Premium in every aspect, this sofa is crafted with elevated comfort in mind. Every detail, including the supple combination leather and faux leather upholstery, has been designed and refined to look and feel luxurious.\nWhether you use it as an inviting place to lounge or pair it with the matching loveseat and accent chair, it's sure to be a rich addition to your home.\n",
  "des-short": "Whether you use it as an inviting place to lounge or pair it with the matching loveseat and accent chair, it's sure to be a rich addition to your home.",
  "material": "Leather",
  "size": "200*100*50",
  "room": "LivingRoom",
  "quantity": 6,
  "image": "./img/img_product/A005.jpg",
  "image-detail": "./img/img_product/A005-d.jpg",
  "path-doc": "./product-detail-doc/A005.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "shoppersChoice", "comment": "Highly recommended! The product is fantastic.", "star": 5, "time": "04/12/2023 09:20:00"},{"user": "bargainHunter", "comment": "Affordable and decent quality. Can't complain.", "star": 4, "time": "04/13/2023 13:10:45"},{"user": "designEnthusiast", "comment": "Unique design, but a bit overpriced. Still, I like it.", "star": 3, "time": "04/14/2023 17:30:30"}]
 },
 {
  "id": 6,
  "pid": "A006",
  "name": "Dellbeck Dining Table With 8 Chairs And Server",
  "price": 1500,
  "brand": "Dunelm Group",
  "description": "Luxurious design, suitable for large families",
  "des-short": "Luxurious design, suitable for large families",
  "material": "Leather",
  "size": "200*100*50",
  "room": "DiningRoom",
  "quantity": 9,
  "image": "./img/img_product/A006.jpg",
  "image-detail": "./img/img_product/A006-d.jpg",
  "path-doc": "./product-detail-doc/A006.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "homedecorFanatic", "comment": "Exquisite craftsmanship! Worth every penny.", "star": 5, "time": "05/20/2023 11:45:00"},{"user": "budgetBuyer", "comment": "Not bad for the price, but there are better options out there.", "star": 3, "time": "05/21/2023 15:25:45"},{"user": "styleSeeker", "comment": "Stylish and functional. Happy with the purchase.", "star": 4, "time": "05/22/2023 19:10:30"}]
 },
 {
  "id": 7,
  "pid": "A007",
  "name": "Bolanburg Dining Table, 6 Chairs, and Bench",
  "price": 1700,
  "brand": "French Heritage",
  "description": "Luxurious design, suitable for large families",
  "des-short": "Luxurious design, suitable for large families",
  "material": "Leather",
  "size": "200*100*50",
  "room": "DiningRoom",
  "quantity": 4,
  "image": "./img/img_product/A007.jpg",
  "image-detail": "./img/img_product/A007-d.jpg",
  "path-doc": "./product-detail-doc/A007.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "interiorDesignPro", "comment": "Perfect addition to any modern interior. Love it!", "star": 5, "time": "06/25/2023 10:05:00"},{"user": "savvyShopper", "comment": "Good deal for the quality. No regrets.", "star": 4, "time": "06/26/2023 14:30:45"},{"user": "minimalistLover", "comment": "Simple and elegant. Fits my minimalist aesthetic.", "star": 5, "time": "06/27/2023 18:55:30"}]
 },
 {
  "id": 8,
  "pid": "A008",
  "name": "Valebeck Counter Height Table and 4 Stools",
  "price": 1300,
  "brand": "Ashley",
  "description": "Luxurious design, suitable for large families",
  "des-short": "Luxurious design, suitable for large families",
  "material": "Leather",
  "size": "200*100*50",
  "room": "DiningRoom",
  "quantity": 3,
  "image": "./img/img_product/A008.jpg",
  "image-detail": "./img/img_product/A008-d.jpg",
  "path-doc": "./product-detail-doc/A008.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "valueHunter", "comment": "Exceptional value for the price. Highly recommend.", "star": 5, "time": "07/10/2023 08:45:00"},{"user": "qualityConscious", "comment": "Top-notch quality, but a bit on the expensive side.", "star": 4, "time": "07/11/2023 12:20:45"},{"user": "trendyBuyer", "comment": "On-trend design. A great addition to my home.", "star": 5, "time": "07/12/2023 16:35:30"}]
 },
 {
  "id": 9,
  "pid": "A009",
  "name": "Glory Furniture Aaron G1800-TB-UP Twin Bed , CAPPUCCINO",
  "price": 800,
  "brand": "French Heritage",
  "description": "This Upholstered Bed. EZ to Assemble, Supports are included to hold a Box Spring or Foundation and a Mattress.\nDurable EZ to Clean Faux Leather is wrapped around Wood And Manufactured Wood Frames.",
  "des-short": "Durable EZ to Clean Faux Leather is wrapped around Wood And Manufactured Wood Frames.",
  "material": "Leather",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 9,
  "image": "./img/img_product/A009.jpg",
  "image-detail": "./img/img_product/A009-d.jpg",
  "path-doc": "./product-detail-doc/A009.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "homeMakeover", "comment": "Transformed my space! Love the new look.", "star": 5, "time": "08/15/2023 09:30:00"},{"user": "frugalDecorator", "comment": "Decent quality for the price. Can't complain.", "star": 5, "time": "08/16/2023 13:15:45"},{"user": "fashionableLiving", "comment": "Fashion-forward design. Happy with the purchase.", "star": 4, "time": "08/17/2023 17:40:30"}]
 },
 {
  "id": 10,
  "pid": "A010",
  "name": "Glory Furniture Aaron G1807-TB-UP Twin Bed , APPLE GREEN",
  "price": 750,
  "brand": "Forma Ideale",
  "description": "This upholstered bed is available in a wide assortment of colors and sizes. Easy to assemble, supports are included to hold a box spring or foundation and a mattress.\nDurable easy-to-clean faux leather is wrapped around the wood and manufactured wood frames. Available in Twin, Full, Queen, and King!",
  "des-short": "Available in Twin, Full, Queen, and King!",
  "material": "Leather",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 9,
  "image": "./img/img_product/A010.jpg",
  "image-detail": "./img/img_product/A010-d.jpg",
  "path-doc": "./product-detail-doc/A010.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "modernLiving", "comment": "Fits perfectly with my modern living room. Great buy!", "star": 5, "time": "09/20/2023 10:55:00"},{"user": "bargainChaser", "comment": "Got it on sale. Good deal for the quality.", "star": 4, "time": "09/21/2023 14:30:45"},{"user": "classicElegance", "comment": "Classic and elegant. Adds a touch of sophistication to my space.", "star": 5, "time": "09/22/2023 18:45:30"}]
 },
 {
  "id": 11,
  "pid": "A011",
  "name": "Glory Furniture Aaron G1825-KB-UP King Bed , DARK RED",
  "price": 800,
  "brand": "Row",
  "description": "This Upholstered Bed. EZ to Assemble, Supports are included to hold a Box Spring or Foundation and a Mattress. Durable EZ to Clean Faux Leather is wrapped around Wood And Manufactured Wood Frames.",
  "des-short": "Durable EZ to Clean Faux Leather is wrapped around Wood And Manufactured Wood Frames.",
  "material": "Leather",
  "size": "200*150*50",
  "room": "BedRoom",
  "quantity": 8,
  "image": "./img/img_product/A011.jpg",
  "image-detail": "./img/img_product/A011-d.jpg",
  "path-doc": "./product-detail-doc/A011.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "tastefulBuyer", "comment": "Tastefully designed. Happy with the overall look.", "star": 4, "time": "10/25/2023 09:10:00"},{"user": "practicalShopper", "comment": "Functional and practical. Exactly what I needed.", "star": 3, "time": "10/26/2023 13:25:45"},{"user": "styleConnoisseur", "comment": "A bit overrated, but the design is appealing.", "star": 4, "time": "10/27/2023 17:50:30"}]
 },
 {
  "id": 12,
  "pid": "A012",
  "name": "Aaron Padded Seat Accent Chair Black",
  "price": 500,
  "brand": "Ashley",
  "description": "High toned Accent Chair, Black- Saltoro Sherpi Injected with sophistication, this Accent Chair will lend a comfortable and relaxed sitting with its plush look. \nShowcasing a subtle black finish, the chair features rustic stitching to count on along with tapered legs.",
  "des-short": "Showcasing a subtle black finish, the chair features rustic stitching to count on along with tapered legs.",
  "material": "Leather",
  "size": "50*50*50",
  "room": "LivingRoom",
  "quantity": 4,
  "image": "./img/img_product/A012.jpg",
  "image-detail": "./img/img_product/A012-d.jpg",
  "path-doc": "./product-detail-doc/A012.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "cozyHomeMaker", "comment": "Creates a cozy atmosphere in my home. Love it!", "star": 5, "time": "11/30/2023 08:20:00"},{"user": "priceSensitiveBuyer", "comment": "Good quality for the price. Satisfied with the purchase.", "star": 4, "time": "11/30/2023 12:45:45"},{"user": "elegantTouch", "comment": "Adds an elegant touch to my home. Happy customer.", "star": 5}]
 },
 {
  "id": 13,
  "pid": "A013",
  "name": "Beautiful Drew Chair by Drew Barrymore, Sage",
  "price": 500,
  "brand": "Aaron",
  "description": "We love the Drew Chair by Beautiful for its wonderful blend of style and comfort. \nThe streamlined design of this oversized boucle swivel accent chair is highlighted by soft, fabric upholstery with natural fibers for an elegant touch and soothing cream tones that compliment a variety of home decor styles and color palettes. \nThe 3 plush accent pillows add customizable comfort. The metal swivel base spins 360 degrees so you can easily direct your attention anywhere in the room. Relax and talk with friends or curl up with a good book, the Drew Chair by Beautiful will be the perfect addition to your living room, reading nook or favorite space.",
  "des-short": "Relax and talk with friends or curl up with a good book, the Drew Chair by Beautiful will be the perfect addition to your living room, reading nook or favorite space.",
  "material": "Leather",
  "size": "50*50*50",
  "room": "LivingRoom",
  "quantity": 4,
  "image": "./img/img_product/A013.jpg",
  "image-detail": "./img/img_product/A013-d.jpg",
  "path-doc": "./product-detail-doc/A013.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "user1", "comment": "This product is very high quality and reasonably priced. I am very satisfied with it. I rate 5 stars", "star": 5, "time": "01/09/2023 07:05:00"},{"user": "user2", "comment": "Bad, I don’t like it", "star": 5, "time": "01/10/2023 21:05:30"},{"user": "user3", "comment": "nice", "star": 4, "time": "06/10/2023 21:50:30"}]
 },
 {
  "id": 14,
  "pid": "A014",
  "name": "Lifestyle Solutions Lorelei Lounge Chair, Navy Blue Fabric",
  "price": 500,
  "brand": "Dunelm Group",
  "description": "The Lorelei collection is for truly authentic living in comfort and cools via this stunning armchair.\n An entire living room collection that is designed and built for ultimate relaxation and comfort for your friends and family, at work or at home. \nThe Lorelei's simple lines enhance any living or workspace with its kiln-dried solid hardwood frame, durable wooden legs, high-density foam seat cushions, removable back cushions, and the highest-end upholstery. Available in gray and blue fabric. A versatile design perfect for any living room, family room, den, home office, or guest room.",
  "des-short": "A versatile design perfect for any living room, family room, den, home office, or guest room.",
  "material": "Leather",
  "size": "50*50*50",
  "room": "LivingRoom",
  "quantity": 8,
  "image": "./img/img_product/A014.jpg",
  "image-detail": "./img/img_product/A014-d.jpg",
  "path-doc": "./product-detail-doc/A014.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "markzuckerberg", "comment": "Good product, great quality, fast shipping, 5 star store", "star": 5, "time": "06/10/2023 20:40:10"},{"user": "sergeybrin", "comment":"The product is very beautiful, very good quality, looks very durable, feels very luxurious", "star": 5, "time": "02/10/2023 12:01:01"},{"user": "larrypage", "comment":"Fast delivery. Correct model. Beautiful for the price. Please rest assured to buy", "star": 5, "time": "20/10-2023 17:30:01"}]
 },
 {
  "id": 15,
  "pid": "A015",
  "name": "Beautiful Wrap Me Up Accent Chair With Removable Cushions by Drew, Cornflower Blue",
  "price": 500,
  "brand": "French Heritage",
  "description": "The Beautiful Wrap Me Up Accent Chair, with its captivating design and inviting features, stands as a testament to both style and comfort. \nWell crafted with a sturdy wood frame, this chair effortlessly blends durability with easy elegance, making it a perfect addition to any living space or reading nook. The frame's sleek lines and graceful curves add an air of refinement, enhancing the chair's overall aesthetic appeal. \nNestled upon the frame are plush, removable cushions that beckon you to sink into their soft embrace. The chair arms are wrapped in a plush cushion as well and are securely attached with snap-on buttons. The chair is available in two sophisticated color options: Cream and Cornflower Blue. Whether you prefer the calming elegance of cornflower blue or the fresh, crisp look of the cream, this chair effortlessly complements any decor. \nWhether you're seeking a statement piece or a cozy retreat, this accent chair embraces you with open arms, inviting you to experience the epitome of comfort and elegance. Pair the Beautiful Wrap Me Up Accent Chair with other items from the Beautiful by Drew Furniture collection to complete your living room (sold separately).",
  "des-short": "Pair the Beautiful Wrap Me Up Accent Chair with other items from the Beautiful by Drew Furniture collection to complete your living room (sold separately).",
  "material": "Leather",
  "size": "50*50*50",
  "room": "LivingRoom",
  "quantity": 5,
  "image": "./img/img_product/A015.jpg",
  "image-detail": "./img/img_product/A015-d.jpg",
  "path-doc": "./product-detail-doc/A015.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "customer1", "comment": "Great product! The quality exceeded my expectations.", "star": 4, "time": "02/15/2023 10:30:00"}, {"user": "customer2", "comment": "Not bad, but a bit pricey for the features it offers.", "star": 3, "time": "02/16/2023 14:20:45"}, {"user": "customer3", "comment": "Impressive design, I love it!", "star": 5, "time": "02/17/2023 18:45:20"}]
 },
 {
  "id": 16,
  "pid": "A016",
  "name": "Fulton Pine Effect Bathroom Toilet Ladder",
  "price": 300,
  "brand": "Ashley",
  "description": "Make the most of the space in your bathroom with this practical yet stylish toilet ladder shelving unit. This smart, space saving unit fits over the toilet to take up no extra space at all. The rustic pine effect finish creates a warming environment and an industrial look that's super on-trend. Featuring two shelves to store a range of items such as diffuser bottles, towels, plants, toiletries, and more.",
  "des-short": "Featuring two shelves to store a range of items such as diffuser bottles, towels, plants, toiletries, and more.",
  "material": "Metal",
  "size": "162*67*35",
  "room": "BathRoom",
  "quantity": 7,
  "image": "./img/img_product/A016.jpg",
  "image-detail": "./img/img_product/A016-d.jpg",
  "path-doc": "./product-detail-doc/A016.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "buyerA", "comment": "Reasonably priced and durable. Satisfied with the purchase.", "star": 4, "time": "03/05/2023 08:15:00"},{"user": "buyerB", "comment": "Could be better. Not the best value for money.", "star": 2, "time": "03/06/2023 12:40:30"},{"user": "buyerC", "comment": "Simple yet elegant design. Happy with my choice.", "star": 5, "time": "03/07/2023 16:55:15"}]
 },
 {
  "id": 17,
  "pid": "A017",
  "name": "Humphrey Bathroom Wall Cabinet",
  "price": 200,
  "brand": "Ashley",
  "description": "Perfect for any smaller bathroom in need of storage, this Humphrey bathroom wall cabinet comes complete with large glass mirror pane that instantly enhances the feeling of light and space in your bathroom. Half of this wall unit has 2 open shelves, making it easy to grab towels and toiletries. The other half is hidden behind a cabinet door and is perfect for medicines and more.",
  "des-short": "The other half is hidden behind a cabinet door and is perfect for medicines and more.",
  "material": "Wood",
  "size": "50*50*50",
  "room": "BathRoom",
  "quantity": 9,
  "image": "./img/img_product/A017.jpg",
  "image-detail": "./img/img_product/A017-d.jpg",
  "path-doc": "./product-detail-doc/A017.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "shoppersChoice", "comment": "Highly recommended! The product is fantastic.", "star": 5, "time": "04/12/2023 09:20:00"},{"user": "bargainHunter", "comment": "Affordable and decent quality. Can't complain.", "star": 4, "time": "04/13/2023 13:10:45"},{"user": "designEnthusiast", "comment": "Unique design, but a bit overpriced. Still, I like it.", "star": 3, "time": "04/14/2023 17:30:30"}]
 },
 {
  "id": 18,
  "pid": "A018",
  "name": "French Cane Laundry Hamper",
  "price": 150,
  "brand": "Ashley",
  "description": "Boasting a rustic French Cane design, this beautiful laundry hamper is ideal for keeping all your washing neat and tidy. Featuring a compact design this hamper is ideal for compact living. Other coordinating French Cane bathroom accessories are also available.",
  "des-short": "Other coordinating French Cane bathroom accessories are also available",
  "material": "Wood",
  "size": "50*50*50",
  "room": "BathRoom",
  "quantity": 5,
  "image": "./img/img_product/A018.jpg",
  "image-detail": "./img/img_product/A018-d.jpg",
  "path-doc": "./product-detail-doc/A018.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "homedecorFanatic", "comment": "Exquisite craftsmanship! Worth every penny.", "star": 5, "time": "05/20/2023 11:45:00"},{"user": "budgetBuyer", "comment": "Not bad for the price, but there are better options out there.", "star": 3, "time": "05/21/2023 15:25:45"},{"user": "styleSeeker", "comment": "Stylish and functional. Happy with the purchase.", "star": 4, "time": "05/22/2023 19:10:30"}]
 },
 {
  "id": 19,
  "pid": "A019",
  "name": "Indi 1 Drawer Dressing Table, Mango Wood",
  "price": 150,
  "brand": "Ashley",
  "description": "Bringing a modern flair to a retro style, the Indi range is perfect for any contemporary or global styled home. Characterised by the stunning rattan fronts and brass knobs, this range boasts a 100% mango wood construction and minimal assembly. Perfect for bringing a warm neutral feel to your home, this beautiful dressing table including an angled mirror and drawers for space to keep your bedroom clutter free. Crafted from sturdy, solid mango wood, this piece is built to last.",
  "des-short": "Crafted from sturdy, solid mango wood, this piece is built to last.",
  "material": "Wood",
  "size": "50*50*50",
  "room": "BedRoom",
  "quantity": 8,
  "image": "./img/img_product/A019.jpg",
  "image-detail": "./img/img_product/A019-d.jpg",
  "path-doc": "./product-detail-doc/A019.docx",
  "isNew": false,
  "isBest": true,
  "discount": 0,
  "review": [{"user": "interiorDesignPro", "comment": "Perfect addition to any modern interior. Love it!", "star": 5, "time": "06/25/2023 10:05:00"},{"user": "savvyShopper", "comment": "Good deal for the quality. No regrets.", "star": 4, "time": "06/26/2023 14:30:45"},{"user": "minimalistLover", "comment": "Simple and elegant. Fits my minimalist aesthetic.", "star": 5, "time": "06/27/2023 18:55:30"}]
 },
 {
  "id": 20,
  "pid": "A020",
  "name": "Indi 2 Drawer Bedside Table, Mango Wood",
  "price": 150,
  "brand": "Aaron",
  "description": "Bringing a modern flair to a retro style, the Indi range is perfect for any contemporary or global styled home. Characterised by the stunning rattan fronts and brass knobs, this range boasts a 100% mango wood construction and minimal assembly. Perfect for bringing a warm neutral feel to your home, this beautiful dressing table including an angled mirror and drawers for space to keep your bedroom clutter free. Crafted from sturdy, solid mango wood, this piece is built to last.",
  "des-short": "Crafted from sturdy, solid mango wood, this piece is built to last.",
  "material": "Wood",
  "size": "50*50*50",
  "room": "BedRoom",
  "quantity": 9,
  "image": "./img/img_product/A020.jpg",
  "image-detail": "./img/img_product/A020-d.jpg",
  "path-doc": "./product-detail-doc/A020.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "valueHunter", "comment": "Exceptional value for the price. Highly recommend.", "star": 5, "time": "07/10/2023 08:45:00"},{"user": "qualityConscious", "comment": "Top-notch quality, but a bit on the expensive side.", "star": 4, "time": "07/11/2023 12:20:45"},{"user": "trendyBuyer", "comment": "On-trend design. A great addition to my home.", "star": 5, "time": "07/12/2023 16:35:30"}]
 },
 {
  "id": 21,
  "pid": "A021",
  "name": "Freddie 2 Drawer Bedside Table",
  "price": 150,
  "brand": "Dunelm Group",
  "description": "Bringing a modern flair to a retro style, the Indi range is perfect for any contemporary or global styled home. Characterised by the stunning rattan fronts and brass knobs, this range boasts a 100% mango wood construction and minimal assembly. Perfect for bringing a warm neutral feel to your home, this beautiful dressing table including an angled mirror and drawers for space to keep your bedroom clutter free. Crafted from sturdy, solid mango wood, this piece is built to last.",
  "des-short": "Crafted from sturdy, solid mango wood, this piece is built to last.",
  "material": "Wood",
  "size": "50*50*50",
  "room": "BedRoom",
  "quantity": 3,
  "image": "./img/img_product/A021.jpg",
  "image-detail": "./img/img_product/A021-d.jpg",
  "path-doc": "./product-detail-doc/A021.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "homeMakeover", "comment": "Transformed my space! Love the new look.", "star": 5, "time": "08/15/2023 09:30:00"},{"user": "frugalDecorator", "comment": "Decent quality for the price. Can't complain.", "star": 5, "time": "08/16/2023 13:15:45"},{"user": "fashionableLiving", "comment": "Fashion-forward design. Happy with the purchase.", "star": 4, "time": "08/17/2023 17:40:30"}]
 },
 {
  "id": 22,
  "pid": "A022",
  "name": "Ashton Metal Extendable Curtain Pole",
  "price": 100,
  "brand": "French Heritage",
  "description": "Supplied with all fixtures and fittings, this stylish metal extendable metal pole is available in a choice of finishes and is for suitable for hanging medium to heavyweight curtains. The extendable telescopic design allows for easy fitting to a range of window sizes without the need to cut it down.",
  "des-short": "The extendable telescopic design allows for easy fitting to a range of window sizes without the need to cut it down.",
  "material": "Metal",
  "size": "25*28",
  "room": "BedRoom",
  "quantity": 8,
  "image": "./img/img_product/A022.jpg",
  "image-detail": "./img/img_product/A022-d.jpg",
  "path-doc": "./product-detail-doc/A022.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "modernLiving", "comment": "Fits perfectly with my modern living room. Great buy!", "star": 5, "time": "09/20/2023 10:55:00"},{"user": "bargainChaser", "comment": "Got it on sale. Good deal for the quality.", "star": 4, "time": "09/21/2023 14:30:45"},{"user": "classicElegance", "comment": "Classic and elegant. Adds a touch of sophistication to my space.", "star": 5, "time": "09/22/2023 18:45:30"}]
 },
 {
  "id": 23,
  "pid": "A023",
  "name": "Realyn 60 Home Office Desk with USB Charging",
  "price": 380,
  "brand": "Forma Ideale",
  "description": "Realyn 60 Home Office Desk with USB Charging",
  "des-short": "Antiqued two-tone aesthetic blends a chipped white with a distressed wood tone top for added charm.",
  "material": "wood, engineered wood and veneers,",
  "size": "60*31*28",
  "room": "WorkRoom",
  "quantity": 4,
  "image": "./img/img_product/A023.png",
  "image-detail": "./img/img_product/A023-d.jpg",
  "path-doc": "./product-detail-doc/A023.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "tastefulBuyer", "comment": "Tastefully designed. Happy with the overall look.", "star": 4, "time": "10/25/2023 09:10:00"},{"user": "practicalShopper", "comment": "Functional and practical. Exactly what I needed.", "star": 3, "time": "10/26/2023 13:25:45"},{"user": "styleConnoisseur", "comment": "A bit overrated, but the design is appealing.", "star": 4, "time": "10/27/2023 17:50:30"}]
 },
 {
  "id": 24,
  "pid": "A024",
  "name": "Realyn 75 Bookcase with 3 Shelves",
  "price": 370,
  "brand": "Row",
  "description": "Elevating the art of traditional cottage styling, the Realyn bookcase is your heavenly home office realized. Antiqued two-tone aesthetic blends a chipped white with a distressed wood tone top for added charm. Clever balance of shelf and drawer space beautifully works.",
  "des-short": "Antiqued two-tone aesthetic blends a chipped white with a distressed wood tone top for added charm",
  "material": "wood, engineered wood and veneers",
  "size": "45*75*16",
  "room": "WorkRoom",
  "quantity": 8,
  "image": "./img/img_product/A024.png",
  "image-detail": "./img/img_product/A024-d.jpg",
  "path-doc": "./product-detail-doc/A024.docx",
  "isNew": true,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "cozyHomeMaker", "comment": "Creates a cozy atmosphere in my home. Love it!", "star": 5, "time": "11/30/2023 08:20:00"},{"user": "priceSensitiveBuyer", "comment": "Good quality for the price. Satisfied with the purchase.", "star": 4, "time": "11/30/2023 12:45:45"},{"user": "elegantTouch", "comment": "Adds an elegant touch to my home. Happy customer.", "star": 5}]
 },
 {
  "id": 25,
  "pid": "A025",
  "name": "Crosley Tall Linen Storage Cabinet",
  "price": 235,
  "brand": "Aaron",
  "description": "Not quite ready for the inconvenience and expense of a complete bathroom remodel? This line of stylish storage solutions will help you create the bathroom of your dreams. The high-end design of this tall cabinet keeps your bathroom essentials neatly stored away and still close at hand. Open upper shelving is ideal for display, while roomy drawers contain smaller items and lower cabinet hides the rest. At home in the tightest or most spacious bath, its compact footprint allows you to live large in small places.",
  "des-short": "Not quite ready for the inconvenience and expense of a complete bathroom remodel?",
  "material": "wood, veneers and engineered wood",
  "size": "24*60*11",
  "room": "BathRoom",
  "quantity": 3,
  "image": "./img/img_product/A025.png",
  "image-detail": "./img/img_product/A025-d.png",
  "path-doc": "./product-detail-doc/A025.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "user1", "comment": "This product is very high quality and reasonably priced. I am very satisfied with it. I rate 5 stars", "star": 5, "time": "01/09/2023 07:05:00"},{"user": "user2", "comment": "Bad, I don’t like it", "star": 5, "time": "01/10/2023 21:05:30"},{"user": "user3", "comment": "nice", "star": 4, "time": "06/10/2023 21:50:30"}]
 },
 {
  "id": 26,
  "pid": "A026",
  "name": "Vedette 5-Basket Storage Tower",
  "price": 160,
  "brand": "Dunelm Group",
  "description": "Fresh as a coastal breeze, this pretty and practical five-basket storage tower works equally well in a bathroom or bedroom. Crafted of pine with a painted finish, the simple frame has rattan weave pull out drawers for easy organizing.",
  "des-short": "Fresh as a coastal breeze, this pretty and practical five-basket storage tower works equally well in a bathroom or bedroom.",
  "material": "pine wood and rattan",
  "size": "17*46*13",
  "room": "BathRoom",
  "quantity": 4,
  "image": "./img/img_product/A026.png",
  "image-detail": "./img/img_product/A026-d.jpg",
  "path-doc": "./product-detail-doc/A026.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "markzuckerberg", "comment": "Good product, great quality, fast shipping, 5 star store", "star": 5, "time": "06/10/2023 20:40:10"},{"user": "sergeybrin", "comment":"The product is very beautiful, very good quality, looks very durable, feels very luxurious", "star": 5, "time": "02/10/2023 12:01:01"},{"user": "larrypage", "comment":"Fast delivery. Correct model. Beautiful for the price. Please rest assured to buy", "star": 5, "time": "20/10-2023 17:30:01"}]
 },
 {
  "id": 27,
  "pid": "A027",
  "name": "Linon Bracken Tall Cabinet",
  "price": 150,
  "brand": "French Heritage",
  "description": "The Bracken tall cabinet takes advantage of vertical space providing ample storage and display space for linens and bathroom necessities. One door keeps the three lower shelves hidden, while three upper shelves are open for easy access. Crafted from solid bamboo, the piece is both sturdy and durable.",
  "des-short": "The Bracken tall cabinet takes advantage of vertical space providing ample storage and display space for linens and bathroom necessities.",
  "material": "solid bamboo",
  "size": "16*61*11",
  "room": "BathRoom",
  "quantity": 5,
  "image": "./img/img_product/A027.png",
  "image-detail": "./img/img_product/A027-d.jpg",
  "path-doc": "./product-detail-doc/A027.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "customer1", "comment": "Great product! The quality exceeded my expectations.", "star": 4, "time": "02/15/2023 10:30:00"}, {"user": "customer2", "comment": "Not bad, but a bit pricey for the features it offers.", "star": 3, "time": "02/16/2023 14:20:45"}, {"user": "customer3", "comment": "Impressive design, I love it!", "star": 5, "time": "02/17/2023 18:45:20"}]
 },
 {
  "id": 28,
  "pid": "A028",
  "name": "Crosley Lydia Over the Toilet Cabinet",
  "price": 160,
  "brand": "Forma Ideale",
  "description": "Bring a sense of order to your bathroom with this chic shelved tower. Designed to add much-needed bathroom storage, its roomy cabinet, open shelf and assortment of hooks provide an elegant use of space. At home in the tightest or most spacious bath, its compact footprint allows you to live large in small places.",
  "des-short": "Pine frame with white finish",
  "material": "Pine",
  "size": "27*67*11",
  "room": "BathRoom",
  "quantity": 5,
  "image": "./img/img_product/A028.png",
  "image-detail": "./img/img_product/A028-d.png",
  "path-doc": "./product-detail-doc/A028.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "buyerA", "comment": "Reasonably priced and durable. Satisfied with the purchase.", "star": 4, "time": "03/05/2023 08:15:00"},{"user": "buyerB", "comment": "Could be better. Not the best value for money.", "star": 2, "time": "03/06/2023 12:40:30"},{"user": "buyerC", "comment": "Simple yet elegant design. Happy with my choice.", "star": 5, "time": "03/07/2023 16:55:15"}]
 },
 {
  "id": 29,
  "pid": "A029",
  "name": "Crosley Savannah Wall Cabinet",
  "price": 105,
  "brand": "Row",
  "description": "ncorporate streamlined storage in your bathroom with the savannah wall cabinet. Two cabinet doors open to a pair of adjustable shelves, ideal for your toiletries or medicine. Mounted securely to the wall, the savannah wall cabinet has lovely shaker style panels and genuine metal hardware that complements a variety of home décor.",
  "des-short": "Two cabinet doors open to a pair of adjustable shelves, ideal for your toiletries or medicine",
  "material": "Alloy",
  "size": "22*26*8",
  "room": "BathRoom",
  "quantity": 5,
  "image": "./img/img_product/A029.png",
  "image-detail": "./img/img_product/A029-d.jpg",
  "path-doc": "./product-detail-doc/A029.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "shoppersChoice", "comment": "Highly recommended! The product is fantastic.", "star": 5, "time": "04/12/2023 09:20:00"},{"user": "bargainHunter", "comment": "Affordable and decent quality. Can't complain.", "star": 4, "time": "04/13/2023 13:10:45"},{"user": "designEnthusiast", "comment": "Unique design, but a bit overpriced. Still, I like it.", "star": 3, "time": "04/14/2023 17:30:30"}]
 },
 {
  "id": 30,
  "pid": "A030",
  "name": "Langford Queen Upholstered Bed",
  "price": 1100,
  "brand": "Forma Ideale",
  "description": "Balancing chic flair with a relaxed sensibility, the Langford upholstered bed strikes just the right tone for sleek sophistication. A merger of beautifully clean lines with cushioned comfort, the headboard is layered with two plush pillows for an indulgent lay-back experience that captures the look and feel of contemporary design, while the extra-wide rails reinvent bedside seating.",
  "des-short": "Includes upholstered panel bed (headboard, footboard and rails)",
  "material": "polyester",
  "size": "79*49*99",
  "room": "BedRoom",
  "quantity": 3,
  "image": "./img/img_product/A030.png",
  "image-detail": "./img/img_product/A030-d.png",
  "path-doc": "./product-detail-doc/A030.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "homedecorFanatic", "comment": "Exquisite craftsmanship! Worth every penny.", "star": 5, "time": "05/20/2023 11:45:00"},{"user": "budgetBuyer", "comment": "Not bad for the price, but there are better options out there.", "star": 3, "time": "05/21/2023 15:25:45"},{"user": "styleSeeker", "comment": "Stylish and functional. Happy with the purchase.", "star": 4, "time": "05/22/2023 19:10:30"}]
 },
 {
  "id": 31,
  "pid": "A031",
  "name": "Langford 6 Drawer Dresser and Mirror",
  "price": 1200,
  "brand": "Row",
  "description": "Balancing chic flair with a relaxed sensibility, the Langford dresser and mirror set strikes just the right tone for rustic sophistication. Beautifully clean lines are subtly enhanced with a weathered gray finish and rough-sawn texture. Hardware-less approach keeps this dresser ultra minimal in design with maximum style. Quality dovetail construction reflects attention to detail from the inside out.",
  "des-short": "eautifully clean lines are subtly enhanced with a weathered gray finish and rough-sawn texture.",
  "material": "pine wood, pine veneer and engineered wood",
  "size": "63*76*18",
  "room": "BedRoom",
  "quantity": 9,
  "image": "./img/img_product/A031.png",
  "image-detail": "./img/img_product/A031-d.jpg",
  "path-doc": "./product-detail-doc/A031.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "interiorDesignPro", "comment": "Perfect addition to any modern interior. Love it!", "star": 5, "time": "06/25/2023 10:05:00"},{"user": "savvyShopper", "comment": "Good deal for the quality. No regrets.", "star": 4, "time": "06/26/2023 14:30:45"},{"user": "minimalistLover", "comment": "Simple and elegant. Fits my minimalist aesthetic.", "star": 5, "time": "06/27/2023 18:55:30"}]
 },
 {
  "id": 32,
  "pid": "A032",
  "name": "Altari Sofa",
  "price": 400,
  "brand": "Forma Ideale",
  "description": "If style is the question, then the Altari sofa is the answer. Sporting clean lines and sleek track arms, the decidedly contemporary profile is enhanced with plump cushioning and a chenille-feel upholstery, so pleasing to the touch. Sure to play well with so many color schemes, this sofa in slate gray includes a pair of understated floral pattern pillows for fashionably fresh appeal.",
  "des-short": "porting clean lines and sleek track arms, the decidedly contemporary profile is enhanced with plump cushioning and a chenille-feel upholstery, so pleasing to the touch.",
  "material": "Polyester (100)%",
  "size": "85*37*38",
  "room": "LivingRoom",
  "quantity": 7,
  "image": "./img/img_product/A032.png",
  "image-detail": "./img/img_product/A032-d.png",
  "path-doc": "./product-detail-doc/A032.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "valueHunter", "comment": "Exceptional value for the price. Highly recommend.", "star": 5, "time": "07/10/2023 08:45:00"},{"user": "qualityConscious", "comment": "Top-notch quality, but a bit on the expensive side.", "star": 4, "time": "07/11/2023 12:20:45"},{"user": "trendyBuyer", "comment": "On-trend design. A great addition to my home.", "star": 5, "time": "07/12/2023 16:35:30"}]
 },
 {
  "id": 33,
  "pid": "A033",
  "name": "Altari Manual Recliner",
  "price": 400,
  "brand": "Row",
  "description": "If style is the question, then the Altari rocker recliner is the answer. Clean-lined profile is beautifully contemporary. Plush chenille fabric and plump cushioning make it so easy to comfortably kick up your heels. Richly neutral hue complements a variety of decor.",
  "des-short": "Clean-lined profile is beautifully contemporary",
  "material": "Polyester",
  "size": "34*40*39",
  "room": "LivingRoom",
  "quantity": 3,
  "image": "./img/img_product/A033.png",
  "image-detail": "./img/img_product/A033-d.png",
  "path-doc": "./product-detail-doc/A033.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "homeMakeover", "comment": "Transformed my space! Love the new look.", "star": 5, "time": "08/15/2023 09:30:00"},{"user": "frugalDecorator", "comment": "Decent quality for the price. Can't complain.", "star": 5, "time": "08/16/2023 13:15:45"},{"user": "fashionableLiving", "comment": "Fashion-forward design. Happy with the purchase.", "star": 4, "time": "08/17/2023 17:40:30"}]
 },
 {
  "id": 34,
  "pid": "A034",
  "name": "Skempton Counter Height Dining Table with Built-In Wine Rack and Shelves",
  "price": 330,
  "brand": "Aaron",
  "description": "The Skempton counter height table with storage invites you to raise the bar on small space living. An inspired choice for coastal chic or modern farmhouse settings, this clean-lined, simply striking table doubles the charm with a brown tone top with plank effect, paired with a grayish white base with rub through effect for timeworn appeal. Built-in 8-bottle wine rack and pair of open shelves make the most of every inch of space.",
  "des-short": "The Skempton counter height table with storage invites you to raise the bar on small space living",
  "material": "solid wood, engineered wood and acacia veneers",
  "size": "60*36*30",
  "room": "DiningRoom",
  "quantity": 8,
  "image": "./img/img_product/A034.png",
  "image-detail": "./img/img_product/A034-d.png",
  "path-doc": "./product-detail-doc/A034.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "modernLiving", "comment": "Fits perfectly with my modern living room. Great buy!", "star": 5, "time": "09/20/2023 10:55:00"},{"user": "bargainChaser", "comment": "Got it on sale. Good deal for the quality.", "star": 4, "time": "09/21/2023 14:30:45"},{"user": "classicElegance", "comment": "Classic and elegant. Adds a touch of sophistication to my space.", "star": 5, "time": "09/22/2023 18:45:30"}]
 },
 {
  "id": 35,
  "pid": "A035",
  "name": "Skempton Storage Dining Table with 2 Side Drawers",
  "price": 350,
  "brand": "Dunelm Group",
  "description": "Set the scene for coastal chic or modern farmhouse living with the Skempton dining room table. Clean-lined, simply striking table doubles the charm with a brown tone top with plank effect, paired with a grayish white base with rub through effect for timeworn appeal. Multi-functional dining table features two convenient side drawers and a storage bin on each end for maximum use of space. Styled to comfortably seat six, this table makes room for one and all.",
  "des-short": "Styled to comfortably seat six, this table makes room for one and all.",
  "material": "wood, acacia veneer and engineered wood",
  "size": "36*30*66",
  "room": "DiningRoom",
  "quantity": 6,
  "image": "./img/img_product/A035.png",
  "image-detail": "./img/img_product/A035-d.png",
  "path-doc": "./product-detail-doc/A035.docx",
  "isNew": false,
  "isBest": false,
  "discount": 15,
  "review": [{"user": "tastefulBuyer", "comment": "Tastefully designed. Happy with the overall look.", "star": 4, "time": "10/25/2023 09:10:00"},{"user": "practicalShopper", "comment": "Functional and practical. Exactly what I needed.", "star": 3, "time": "10/26/2023 13:25:45"},{"user": "styleConnoisseur", "comment": "A bit overrated, but the design is appealing.", "star": 4, "time": "10/27/2023 17:50:30"}]
 },
 {
  "id": 36,
  "pid": "A036",
  "name": "Skempton Ladderback Dining Chair with Upholstered Seat",
  "price": 180,
  "brand": "French Heritage",
  "description": "The Skempton dining chair invites you to raise the bar for small space living. An inspired choice for coastal chic or modern farmhouse settings, this comfortably cushioned chair sports a grayish white finish with rub through effect for timeworn appeal.",
  "des-short": "The Skempton dining chair invites you to raise the bar for small space living. An inspired choice for coastal chic or modern farmhouse settings, this comfortably cushioned chair sports a grayish white finish with rub through effect for timeworn appeal.",
  "material": "wood and engineered wood",
  "size": "18*39*21",
  "room": "DiningRoom",
  "quantity": 6,
  "image": "./img/img_product/A036.png",
  "image-detail": "./img/img_product/A036-d.png",
  "path-doc": "./product-detail-doc/A036.docx",
  "isNew": false,
  "isBest": false,
  "discount": 20,
  "review": [{"user": "cozyHomeMaker", "comment": "Creates a cozy atmosphere in my home. Love it!", "star": 5, "time": "11/30/2023 08:20:00"},{"user": "priceSensitiveBuyer", "comment": "Good quality for the price. Satisfied with the purchase.", "star": 4, "time": "11/30/2023 12:45:45"},{"user": "elegantTouch", "comment": "Adds an elegant touch to my home. Happy customer.", "star": 5}]
 },
 {
  "id": 37,
  "pid": "A037",
  "name": "Caitbrook Counter Height Dining Table with Shelves",
  "price": 300,
  "brand": "Forma Ideale",
  "description": "Perfect portion. Striking a simply chic pose, the Caitbrook dining room counter height table serves up high style on a smaller scale. Its antiqued gray wash finish gives the clean-lined design a casually cool sensibility. Side shelves cleverly balance form and function.",
  "des-short": "Perfect portion.",
  "material": "veneers, wood and engineered wood",
  "size": "60*26*30",
  "room": "DiningRoom",
  "quantity": 5,
  "image": "./img/img_product/A037.png",
  "image-detail": "./img/img_product/A037-d.png",
  "path-doc": "./product-detail-doc/A037.docx",
  "isNew": false,
  "isBest": false,
  "discount": 35,
  "review": [{"user": "user1", "comment": "This product is very high quality and reasonably priced. I am very satisfied with it. I rate 5 stars", "star": 5, "time": "01/09/2023 07:05:00"},{"user": "user2", "comment": "Bad, I don’t like it", "star": 5, "time": "01/10/2023 21:05:30"},{"user": "user3", "comment": "nice", "star": 4, "time": "06/10/2023 21:50:30"}]
 },
 {
  "id": 38,
  "pid": "A038",
  "name": "Caitbrook Counter Height Backless Bar Stool",
  "price": 120,
  "brand": "Row",
  "description": "Bring a relaxed yet refined sense of good taste to a space with the Caitbrook upholstered stool. The clean-lined frame sports a gray-washed finish that’s so easy on the eyes. Covered in a complementary textured gray fabric, the stool’s cushioned upholstered seat goes easy on the body.",
  "des-short": "The clean-lined frame sports a gray-washed finish that’s so easy on the eye",
  "material": "solid acacia wood",
  "size": "21*24*16",
  "room": "DiningRoom",
  "quantity": 6,
  "image": "./img/img_product/A038.png",
  "image-detail": "./img/img_product/A038-d.jpg",
  "path-doc": "./product-detail-doc/A038.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "markzuckerberg", "comment": "Good product, great quality, fast shipping, 5 star store", "star": 5, "time": "06/10/2023 20:40:10"},{"user": "sergeybrin", "comment":"The product is very beautiful, very good quality, looks very durable, feels very luxurious", "star": 5, "time": "02/10/2023 12:01:01"},{"user": "larrypage", "comment":"Fast delivery. Correct model. Beautiful for the price. Please rest assured to buy", "star": 5, "time": "20/10-2023 17:30:01"}]
 },
 {
  "id": 39,
  "pid": "A039",
  "name": "Realyn 60 L-Shaped Home Office Lift Top Desk with USB Charging",
  "price": 650,
  "brand": "Ashley",
  "description": "Elevating the art of traditional cottage styling, the Realyn L-shaped desk is your heavenly home office realized. Two-tone finish combines chipped white with distressed wood tone tops for added charm. Framed drawer fronts, decorative corbels and elegantly turned and tapered legs add refinement, while dark bronze-tone knobs lend a classic touch. Spring lift top raises the surface to a comfortable standing position, for a healthy alternative. Built for looks and productivity, the built-in power supply and dual USB ports keep your devices close at hand and ready to go.",
  "des-short": "Two-tone finish combines chipped white with distressed wood tone tops for added charm",
  "material": "wood, engineered wood and veneers,",
  "size": "60*31*76",
  "room": "WorkRoom",
  "quantity": 7,
  "image": "./img/img_product/A039.png",
  "image-detail": "./img/img_product/A039-d.png",
  "path-doc": "./product-detail-doc/A039.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "customer1", "comment": "Great product! The quality exceeded my expectations.", "star": 4, "time": "02/15/2023 10:30:00"}, {"user": "customer2", "comment": "Not bad, but a bit pricey for the features it offers.", "star": 3, "time": "02/16/2023 14:20:45"}, {"user": "customer3", "comment": "Impressive design, I love it!", "star": 5, "time": "02/17/2023 18:45:20"}]
 },
 {
  "id": 40,
  "pid": "A040",
  "name": "Carynhurst 60 Home Office Desk",
  "price": 230,
  "brand": "Aaron",
  "description": "Looking for a fresh approach to modern farmhouse living? The Carynhurst home office desk works on so many levels. Two smooth-gliding drawers with dovetail construction reflect high quality that never goes out of fashion. Whitewash finish is a mastery in subtle sophistication.",
  "des-short": "Two smooth-gliding drawers with dovetail construction reflect high quality that never goes out of fashion.",
  "material": "pine veneers, pine wood and engineered wood",
  "size": "60*31*26",
  "room": "WorkRoom",
  "quantity": 5,
  "image": "./img/img_product/A040.png",
  "image-detail": "./img/img_product/A040-d.png",
  "path-doc": "./product-detail-doc/A040.docx",
  "isNew": false,
  "isBest": false,
  "discount": 15,
  "review": [{"user": "buyerA", "comment": "Reasonably priced and durable. Satisfied with the purchase.", "star": 4, "time": "03/05/2023 08:15:00"},{"user": "buyerB", "comment": "Could be better. Not the best value for money.", "star": 2, "time": "03/06/2023 12:40:30"},{"user": "buyerC", "comment": "Simple yet elegant design. Happy with my choice.", "star": 5, "time": "03/07/2023 16:55:15"}]
 },
 {
  "id": 41,
  "pid": "A041",
  "name": "Carynhurst 75 Bookcase with 4 Shelves",
  "price": 370,
  "brand": "Dunelm Group",
  "description": "Looking for a fresh approach to modern farmhouse living? The Carynhurst bookcase works on so many levels. Clean-lined profile with crossbuck back never goes out of fashion. Whitewash finish is a mastery in subtle sophistication.",
  "des-short": "The Carynhurst bookcase works on so many levels. Clean-lined profile with crossbuck back never goes out of fashion.",
  "material": "pine veneers, pine wood and engineered wood",
  "size": "38*78*16",
  "room": "WorkRoom",
  "quantity": 8,
  "image": "./img/img_product/A041.png",
  "image-detail": "./img/img_product/A041-d.jpg",
  "path-doc": "./product-detail-doc/A041.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "shoppersChoice", "comment": "Highly recommended! The product is fantastic.", "star": 5, "time": "04/12/2023 09:20:00"},{"user": "bargainHunter", "comment": "Affordable and decent quality. Can't complain.", "star": 4, "time": "04/13/2023 13:10:45"},{"user": "designEnthusiast", "comment": "Unique design, but a bit overpriced. Still, I like it.", "star": 3, "time": "04/14/2023 17:30:30"}]
 },
 {
  "id": 42,
  "pid": "A042",
  "name": "Carynhurst 2 Drawer Printer Stand with USB Charging",
  "price": 170,
  "brand": "French Heritage",
  "description": "Set on casters for easy mobility, the Carynhurst printer stand rolls out a fresh look in modern farmhouse living. Two smooth-gliding drawers with dovetail construction reflect high quality that never goes out of fashion. Pair of electrical outlets and USB charging ports make it an indispensable home office essential.",
  "des-short": "Pair of electrical outlets and USB charging ports make it an indispensable home office essential.",
  "material": "pine veneers, pine wood and engineered wood",
  "size": "21*25*18",
  "room": "WorkRoom",
  "quantity": 3,
  "image": "./img/img_product/A042.png",
  "image-detail": "./img/img_product/A042-d.png",
  "path-doc": "./product-detail-doc/A042.docx",
  "isNew": false,
  "isBest": false,
  "discount": 15,
  "review": [{"user": "homedecorFanatic", "comment": "Exquisite craftsmanship! Worth every penny.", "star": 5, "time": "05/20/2023 11:45:00"},{"user": "budgetBuyer", "comment": "Not bad for the price, but there are better options out there.", "star": 3, "time": "05/21/2023 15:25:45"},{"user": "styleSeeker", "comment": "Stylish and functional. Happy with the purchase.", "star": 4, "time": "05/22/2023 19:10:30"}]
 },
 {
  "id": 43,
  "pid": "A043",
  "name": "Baraga 61 Modular L-Shaped Home Office Desk",
  "price": 240,
  "brand": "Forma Ideale",
  "description": "The Baraga L-desk delivers the functionality you crave with the modern style that suits your taste. Frosted glass appears to float over the streamlined metal base. The desk's L-shape design sets up two different ways, enabling left-handed and right-handed users to maximize their workspace.",
  "des-short": "The Baraga L-desk delivers the functionality you crave with the modern style that suits your taste",
  "material": "glass and metal",
  "size": "61*30*51",
  "room": "WorkRoom",
  "quantity": 7,
  "image": "./img/img_product/A043.png",
  "image-detail": "./img/img_product/A043-d.png",
  "path-doc": "./product-detail-doc/A043.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "interiorDesignPro", "comment": "Perfect addition to any modern interior. Love it!", "star": 5, "time": "06/25/2023 10:05:00"},{"user": "savvyShopper", "comment": "Good deal for the quality. No regrets.", "star": 4, "time": "06/26/2023 14:30:45"},{"user": "minimalistLover", "comment": "Simple and elegant. Fits my minimalist aesthetic.", "star": 5, "time": "06/27/2023 18:55:30"}]
 },
 {
  "id": 44,
  "pid": "A044",
  "name": "Baraga Swivel Home Office Desk Chair",
  "price": 200,
  "brand": "Row",
  "description": "Baraga swivel desk chair delivers the comfort you crave with the modern style that suits your taste. Sleek, linear design and faux leather maximize a minimalist look. Casters, adjustable seat and 360-degree swivel make this functional piece all the more flexible.",
  "des-short": "Casters, adjustable seat and 360-degree swivel make this functional piece all the more flexible.",
  "material": "metal",
  "size": "24*35*25",
  "room": "WorkRoom",
  "quantity": 6,
  "image": "./img/img_product/A044.png",
  "image-detail": "./img/img_product/A044-d.jpg",
  "path-doc": "./product-detail-doc/A044.docx",
  "isNew": false,
  "isBest": false,
  "discount": 15,
  "review": [{"user": "valueHunter", "comment": "Exceptional value for the price. Highly recommend.", "star": 5, "time": "07/10/2023 08:45:00"},{"user": "qualityConscious", "comment": "Top-notch quality, but a bit on the expensive side.", "star": 4, "time": "07/11/2023 12:20:45"},{"user": "trendyBuyer", "comment": "On-trend design. A great addition to my home.", "star": 5, "time": "07/12/2023 16:35:30"}]
 },
 {
  "id": 45,
  "pid": "A045",
  "name": "Lettner Twin over Full Bunk Bed with 1 Large Storage Drawer",
  "price": 850,
  "brand": "Ashley",
  "description": "Double the space means twice the fun, and that’s what they’ll enjoy with the Lettner twin-over-full bunk bed. Forever classic design details—under bed storage, a sturdy ladder and safety rails—are paired with a burnished gray finish that elevates the look with modern sensibility.",
  "des-short": "Double the space means twice the fun, and that’s what they’ll enjoy with the Lettner twin-over-full bunk bed",
  "material": "veneers, wood and engineered wood",
  "size": "79*65*56",
  "room": "KidRoom",
  "quantity": 9,
  "image": "./img/img_product/A045.png",
  "image-detail": "./img/img_product/A045-d.png",
  "path-doc": "./product-detail-doc/A045.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "homeMakeover", "comment": "Transformed my space! Love the new look.", "star": 5, "time": "08/15/2023 09:30:00"},{"user": "frugalDecorator", "comment": "Decent quality for the price. Can't complain.", "star": 5, "time": "08/16/2023 13:15:45"},{"user": "fashionableLiving", "comment": "Fashion-forward design. Happy with the purchase.", "star": 4, "time": "08/17/2023 17:40:30"}]
 },
 {
  "id": 46,
  "pid": "A046",
  "name": "Lettner 6 Drawer Youth Dresser and Mirror",
  "price": 730,
  "brand": "Aaron",
  "description": "Satisfying your taste for tradition, the Lettner dresser and mirror set sports serene sophistication. Forever classic design details—inlaid panels, silvertone patina hardware and bun feet—are so easy to love. Six roomy drawers keep your wardrobe organized in style. Beveled mirror frame beautifully echoes the dresser’s burnished light gray finish for modern sensibility.",
  "des-short": "Beveled mirror frame beautifully echoes the dresser’s burnished light gray finish for modern sensibility.",
  "material": "veneers, wood and engineered wood",
  "size": "54*71*17",
  "room": "KidRoom",
  "quantity": 4,
  "image": "./img/img_product/A046.png",
  "image-detail": "./img/img_product/A046-d.png",
  "path-doc": "./product-detail-doc/A046.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "modernLiving", "comment": "Fits perfectly with my modern living room. Great buy!", "star": 5, "time": "09/20/2023 10:55:00"},{"user": "bargainChaser", "comment": "Got it on sale. Good deal for the quality.", "star": 4, "time": "09/21/2023 14:30:45"},{"user": "classicElegance", "comment": "Classic and elegant. Adds a touch of sophistication to my space.", "star": 5, "time": "09/22/2023 18:45:30"}]
 },
 {
  "id": 47,
  "pid": "A047",
  "name": "Realyn Twin Panel Bed",
  "price": 360,
  "brand": "Dunelm Group",
  "description": "Realyn Twin Panel Bed",
  "des-short": "The distressed chipped white finish charms with its heirloom appeal.",
  "material": "eneers, wood and engineered wood",
  "size": "45*58*82",
  "room": "KidRoom",
  "quantity": 4,
  "image": "./img/img_product/A047.png",
  "image-detail": "./img/img_product/A047-d.png",
  "path-doc": "./product-detail-doc/A047.docx",
  "isNew": false,
  "isBest": false,
  "discount": 20,
  "review": [{"user": "tastefulBuyer", "comment": "Tastefully designed. Happy with the overall look.", "star": 4, "time": "10/25/2023 09:10:00"},{"user": "practicalShopper", "comment": "Functional and practical. Exactly what I needed.", "star": 3, "time": "10/26/2023 13:25:45"},{"user": "styleConnoisseur", "comment": "A bit overrated, but the design is appealing.", "star": 4, "time": "10/27/2023 17:50:30"}]
 },
 {
  "id": 48,
  "pid": "A048",
  "name": "Linon Sammy Shark Ottoman",
  "price": 105,
  "brand": "French Heritage",
  "description": "Look out, there's something in the water! Dangerously cute and comfortable, this friendly shark doubles as a plush chair that your kids will love. The comfortable foam padded cushions are wrapped in 100% polyester fabric for easy cleaning and a soft touch, even the teeth! Measuring 15 L x 7 D x 25 H, this is a safe and accessible perch that the whole family will love. Use it as a seat, footstool, a prop in a play or as a platform for arts and crafts. Either way excitement and creativity are sure to follow.",
  "des-short": "The comfortable foam padded cushions are wrapped in 100% polyester fabric for easy cleaning and a soft touch,",
  "material": "polyester",
  "size": "15*25*27",
  "room": "KidRoom",
  "quantity": 6,
  "image": "./img/img_product/A048.png",
  "image-detail": "./img/img_product/A048-d.png",
  "path-doc": "./product-detail-doc/A048.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "cozyHomeMaker", "comment": "Creates a cozy atmosphere in my home. Love it!", "star": 5, "time": "11/30/2023 08:20:00"},{"user": "priceSensitiveBuyer", "comment": "Good quality for the price. Satisfied with the purchase.", "star": 4, "time": "11/30/2023 12:45:45"},{"user": "elegantTouch", "comment": "Adds an elegant touch to my home. Happy customer.", "star": 5}]
 },
 {
  "id": 49,
  "pid": "A049",
  "name": "Delta Children Serta Happy Home Storage Bookcase",
  "price": 223,
  "brand": "Forma Ideale",
  "description": "Perfect for the playroom or a child's bedroom, the Happy Home Storage Bookcase from Serta is the dreamiest way to store books and toys. Sure to inspire hours of imaginative play, this beautifully crafted accent piece features details like a gabled roofline, picket fence trim and strong wood construction. Designed to hold books, toys and more, the Happy Home Storage Bookcase is outfitted with two fixed shelves, plus an open cubby on the bottom for larger items.",
  "des-short": "Designed to hold books, toys and more, the Happy Home Storage Bookcase is outfitted with two fixed shelves, plus an open cubby on the bottom for larger items.",
  "material": "wood",
  "size": "12*45*37",
  "room": "KidRoom",
  "quantity": 6,
  "image": "./img/img_product/A049.jpg",
  "image-detail": "./img/img_product/A049-d.png",
  "path-doc": "./product-detail-doc/A049.docx",
  "isNew": false,
  "isBest": false,
  "discount": 35,
  "review": [{"user": "user1", "comment": "This product is very high quality and reasonably priced. I am very satisfied with it. I rate 5 stars", "star": 5, "time": "01/09/2023 07:05:00"},{"user": "user2", "comment": "Bad, I don’t like it", "star": 5, "time": "01/10/2023 21:05:30"},{"user": "user3", "comment": "nice", "star": 4, "time": "06/10/2023 21:50:30"}]
 },
 {
  "id": 50,
  "pid": "A050",
  "name": "Delta Children Tree Bookcase",
  "price": 208,
  "brand": "Row",
  "description": "Looking for a creative storage option for your child’s playroom our bedroom? Branch out with this Tree Bookcase by Delta Children. This bookcase features a variety of shelves in different shapes and sizes, giving plenty of space to hold toys, books or display décor. And the bottom shelves are easily accessible, so kids can help with the cleanup. Designed with your child’s safety in mind, this bookcase attaches securely to any wall with the included wall anchor. Plus, it’s GREENGUARD Gold Certified, which means it’s built to contribute to cleaner air for a healthy home. Delta Children was founded around the idea of making safe, high-quality children's furniture affordable for all families. They know there's nothing more important than safety when it comes to your child's space. That's why all Delta Children products are built with long-lasting materials to ensure they stand up to years of jumping and playing. Plus, they are rigorously tested to meet or exceed all industry safety standards.",
  "des-short": "This bookcase features a variety of shelves in different shapes and sizes, giving plenty of space to hold toys, books or display décor.",
  "material": "engineered wood",
  "size": "44*50*13",
  "room": "KidRoom",
  "quantity": 3,
  "image": "./img/img_product/A050.png",
  "image-detail": "./img/img_product/A050-d.png",
  "path-doc": "./product-detail-doc/A050.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "markzuckerberg", "comment": "Good product, great quality, fast shipping, 5 star store", "star": 5, "time": "06/10/2023 20:40:10"},{"user": "sergeybrin", "comment":"The product is very beautiful, very good quality, looks very durable, feels very luxurious", "star": 5, "time": "02/10/2023 12:01:01"},{"user": "larrypage", "comment":"Fast delivery. Correct model. Beautiful for the price. Please rest assured to buy", "star": 5, "time": "20/10-2023 17:30:01"}]
 },
 {
  "id": 51,
  "pid": "A051",
  "name": "Delta Children Mysize Double-sided Storage Easel",
  "price": 78,
  "brand": "Ashley",
  "description": "Spark artistic play with the MySize Double-Sided Storage Easel from Delta Children. This two-sided easel for kids features three different drawing surfaces—a chalkboard on one side, a magnetic dry-erase whiteboard on the other, and a pull down paper roll on top (33 feet of paper included). Just the right height for growing artists, this kids' easel encourages creativity and allows little ones to develop their fine motor skills through painting, drawing, coloring and writing. Two storage bins underneath the easel keep art supplies neat and nearby.",
  "des-short": "Just the right height for growing artists, this kids' easel encourages creativity and allows little ones to develop their fine motor skills through painting, drawing, coloring and writing.",
  "material": "pine wood, engineered wood and metal",
  "size": "22*41*20",
  "room": "KidRoom",
  "quantity": 8,
  "image": "./img/img_product/A051.jpg",
  "image-detail": "./img/img_product/A051-d.jpg",
  "path-doc": "./product-detail-doc/A051.docx",
  "isNew": false,
  "isBest": false,
  "discount": 15,
  "review": [{"user": "customer1", "comment": "Great product! The quality exceeded my expectations.", "star": 4, "time": "02/15/2023 10:30:00"}, {"user": "customer2", "comment": "Not bad, but a bit pricey for the features it offers.", "star": 3, "time": "02/16/2023 14:20:45"}, {"user": "customer3", "comment": "Impressive design, I love it!", "star": 5, "time": "02/17/2023 18:45:20"}]
 },
 {
  "id": 52,
  "pid": "A052",
  "name": "Delta Children SpongeBob SquarePants Chair",
  "price": 132,
  "brand": "Ashley",
  "description": "Oh buoy! You know it’s going to be the best day ever when your child is relaxing in this SpongeBob SquarePants High Back Upholstered Chair by Delta Children. An easy way to bring SpongeBob’s bubbly personality to your little one's space, this cozy kids’ chair features his big yellow face, a high, supportive back, plenty of padding and easy-to-clean faux leather upholstery. Built for years of use, this chair’s sturdy hardwood frame is perfectly sized for your growing toddler.",
  "des-short": "Built for years of use, this chair’s sturdy hardwood frame is perfectly sized for your growing toddler.",
  "material": "pine wood, metal and foam",
  "size": "21*25*22",
  "room": "KidRoom",
  "quantity": 7,
  "image": "./img/img_product/A052.png",
  "image-detail": "./img/img_product/A052-d.jpg",
  "path-doc": "./product-detail-doc/A052.docx",
  "isNew": false,
  "isBest": false,
  "discount": 0,
  "review": [{"user": "buyerA", "comment": "Reasonably priced and durable. Satisfied with the purchase.", "star": 4, "time": "03/05/2023 08:15:00"},{"user": "buyerB", "comment": "Could be better. Not the best value for money.", "star": 2, "time": "03/06/2023 12:40:30"},{"user": "buyerC", "comment": "Simple yet elegant design. Happy with my choice.", "star": 5, "time": "03/07/2023 16:55:15"}]
 }
]